[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
script = "scripts"
solc_version = "0.8.20"


optimizer = true
optimizer_runs = 200
via_ir = false

remappings = [
  "@ensdomains/buffer/=lib/buffer/",
  "@ensdomains/ens-contracts/=lib/ens-contracts/",
  "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
