[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
script = "scripts"

optimizer = true
optimizer_runs = 200
via_ir = false

remappings = [
  "@ensdomains/buffer/=lib/buffer/",
  "@ensdomains/ens-contracts/=lib/ens-contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
